//! Syntax highlighting emitted as CSS classes rather than inline styles, so
//! both palettes live once in a stylesheet instead of being repeated on every
//! token of every page.

use anyhow::{Result, anyhow};
use syntect::highlighting::ThemeSet;
use syntect::html::{ClassStyle, ClassedHTMLGenerator, css_for_theme_with_class_style};
use syntect::parsing::SyntaxSet;
use syntect::util::LinesWithEndings;

const STYLE: ClassStyle = ClassStyle::SpacedPrefixed { prefix: "hl-" };

pub struct Highlighter {
    syntaxes: SyntaxSet,
    themes: ThemeSet,
}

impl Highlighter {
    pub fn new() -> Self {
        Self {
            syntaxes: SyntaxSet::load_defaults_newlines(),
            themes: ThemeSet::load_defaults(),
        }
    }

    pub fn to_html(&self, code: &str, lang: &str) -> Result<String> {
        let syntax = self
            .syntaxes
            .find_syntax_by_token(lang)
            .or_else(|| self.syntaxes.find_syntax_by_extension(lang))
            .unwrap_or_else(|| self.syntaxes.find_syntax_plain_text());

        let mut generator =
            ClassedHTMLGenerator::new_with_class_style(syntax, &self.syntaxes, STYLE);

        for line in LinesWithEndings::from(code) {
            generator.parse_html_for_line_which_includes_newline(line)?;
        }

        Ok(format!(
            "<pre class=\"hl-code\"><code>{}</code></pre>",
            generator.finalize()
        ))
    }

    /// Both palettes, written once at build time into public/syntax.css.
    pub fn stylesheet(&self, light: &str, dark: &str) -> Result<String> {
        let light = self
            .themes
            .themes
            .get(light)
            .ok_or_else(|| anyhow!("unknown light theme: {light}"))?;
        let dark = self
            .themes
            .themes
            .get(dark)
            .ok_or_else(|| anyhow!("unknown dark theme: {dark}"))?;

        Ok(format!(
            "/* generated by the site builder - do not edit */\n\
             :root {{ color-scheme: light dark; }}\n\
             {}\n\
             @media (prefers-color-scheme: dark) {{\n{}\n}}\n",
            css_for_theme_with_class_style(light, STYLE)?,
            css_for_theme_with_class_style(dark, STYLE)?,
        ))
    }
}

impl Default for Highlighter {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn emits_classes_not_inline_styles() {
        let hl = Highlighter::new();
        let html = hl.to_html("echo hello\n", "bash").unwrap();
        assert!(html.contains("class=\"hl-"), "expected hl- classes: {html}");
        assert!(!html.contains("style="), "must not inline styles: {html}");
    }

    #[test]
    fn wraps_output_in_a_themed_pre() {
        let hl = Highlighter::new();
        let html = hl.to_html("echo hello\n", "bash").unwrap();
        assert!(html.starts_with("<pre class=\"hl-code\"><code>"));
        assert!(html.ends_with("</code></pre>"));
    }

    #[test]
    fn falls_back_to_plain_text_for_an_unknown_language() {
        let hl = Highlighter::new();
        // Caddyfile has no syntect definition; it must not panic or error.
        let html = hl.to_html("{$APP_DOMAIN} {\n}\n", "caddy").unwrap();
        assert!(html.contains("APP_DOMAIN"));
    }

    #[test]
    fn stylesheet_carries_both_palettes() {
        let hl = Highlighter::new();
        let css = hl
            .stylesheet("Solarized (light)", "base16-ocean.dark")
            .unwrap();
        assert!(css.contains("@media (prefers-color-scheme: dark)"));
        // Solarized light's background, proving the light theme is present.
        assert!(css.to_lowercase().contains("#fdf6e3"));
    }

    #[test]
    fn stylesheet_rejects_an_unknown_theme() {
        let hl = Highlighter::new();
        assert!(hl.stylesheet("No Such Theme", "base16-ocean.dark").is_err());
    }
}
