//! Syntax highlighting emitted as CSS classes rather than inline styles, so
//! both palettes live once in a stylesheet instead of being repeated on every
//! token of every page.

use anyhow::{Result, anyhow};
use syntect::highlighting::ThemeSet;
use syntect::html::{ClassStyle, ClassedHTMLGenerator, css_for_theme_with_class_style};
use syntect::parsing::SyntaxSet;
use syntect::util::LinesWithEndings;

const STYLE: ClassStyle = ClassStyle::SpacedPrefixed { prefix: "hl-" };

pub struct Highlighter {
    syntaxes: SyntaxSet,
    themes: ThemeSet,
}

impl Highlighter {
    pub fn new() -> Self {
        Self {
            syntaxes: SyntaxSet::load_defaults_newlines(),
            themes: ThemeSet::load_defaults(),
        }
    }

    pub fn to_html(&self, code: &str, lang: &str) -> Result<String> {
        let syntax = self
            .syntaxes
            .find_syntax_by_token(lang)
            .or_else(|| self.syntaxes.find_syntax_by_extension(lang))
            .unwrap_or_else(|| self.syntaxes.find_syntax_plain_text());

        let mut generator =
            ClassedHTMLGenerator::new_with_class_style(syntax, &self.syntaxes, STYLE);

        for line in LinesWithEndings::from(code) {
            generator.parse_html_for_line_which_includes_newline(line)?;
        }

        Ok(format!(
            "<pre class=\"hl-code\"><code>{}</code></pre>",
            generator.finalize()
        ))
    }

    /// Both palettes, written once at build time into public/syntax.<hash>.css
    /// -- `main` hashes the returned string and picks the filename, this
    /// function only produces the bytes.
    pub fn stylesheet(&self, light: &str, dark: &str) -> Result<String> {
        let light = self
            .themes
            .themes
            .get(light)
            .ok_or_else(|| anyhow!("unknown light theme: {light}"))?;
        let dark = self
            .themes
            .themes
            .get(dark)
            .ok_or_else(|| anyhow!("unknown dark theme: {dark}"))?;

        let dark_css = css_for_theme_with_class_style(dark, STYLE)?;

        Ok(format!(
            "/* generated by the site builder - do not edit */\n\
             {}\n\
             /* The OS preference, unless an explicit light choice overrides it. */\n\
             @media (prefers-color-scheme: dark) {{\n\
             :root:not([data-theme=\"light\"]) {{\n{}\n}}\n\
             }}\n\
             /* An explicit dark choice, whatever the OS says -- but only on\n\
                screen. site.css forces `color-scheme: light !important` in\n\
                its print block so a saved dark theme still prints light, but\n\
                `color-scheme` cannot reach syntax highlighting: this rule is\n\
                an attribute selector, not something routed through\n\
                light-dark(), so without the @media screen guard it would\n\
                keep outranking print's :root and put a near-black code\n\
                background on a printed page. */\n\
             @media screen {{\n\
             :root[data-theme=\"dark\"] {{\n{}\n}}\n\
             }}\n",
            css_for_theme_with_class_style(light, STYLE)?,
            dark_css,
            dark_css,
        ))
    }
}

impl Default for Highlighter {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn emits_classes_not_inline_styles() {
        let hl = Highlighter::new();
        let html = hl.to_html("echo hello\n", "bash").unwrap();
        assert!(html.contains("class=\"hl-"), "expected hl- classes: {html}");
        assert!(!html.contains("style="), "must not inline styles: {html}");
    }

    #[test]
    fn wraps_output_in_a_themed_pre() {
        let hl = Highlighter::new();
        let html = hl.to_html("echo hello\n", "bash").unwrap();
        assert!(html.starts_with("<pre class=\"hl-code\"><code>"));
        assert!(html.ends_with("</code></pre>"));
    }

    #[test]
    fn falls_back_to_plain_text_for_an_unknown_language() {
        let hl = Highlighter::new();
        // Caddyfile has no syntect definition; it must not panic or error.
        let html = hl.to_html("{$APP_DOMAIN} {\n}\n", "caddy").unwrap();
        assert!(html.contains("APP_DOMAIN"));
    }

    #[test]
    fn stylesheet_carries_both_palettes() {
        let hl = Highlighter::new();
        let css = hl
            .stylesheet("Solarized (light)", "base16-ocean.dark")
            .unwrap();
        assert!(css.contains("@media (prefers-color-scheme: dark)"));
        // Solarized light's background, proving the light theme is present.
        assert!(css.to_lowercase().contains("#fdf6e3"));
    }

    #[test]
    fn stylesheet_rejects_an_unknown_theme() {
        let hl = Highlighter::new();
        assert!(hl.stylesheet("No Such Theme", "base16-ocean.dark").is_err());
    }

    #[test]
    fn stylesheet_follows_the_data_theme_attribute_as_well_as_the_os() {
        let hl = Highlighter::new();
        let css = hl
            .stylesheet("Solarized (light)", "base16-ocean.dark")
            .unwrap();

        // The OS path, but yielding to an explicit light choice.
        assert!(css.contains("prefers-color-scheme: dark"), "got: {css}");
        assert!(css.contains("[data-theme=\"light\"]"), "got: {css}");

        // The explicit dark choice, independent of the OS.
        assert!(css.contains("[data-theme=\"dark\"]"), "got: {css}");
    }

    #[test]
    fn the_explicit_dark_override_is_scoped_to_screen_so_print_can_win() {
        // color-scheme (site.css's print block) cannot influence this
        // attribute selector, so it must be confined to @media screen
        // instead -- otherwise a printed page still gets the dark code
        // background even though every other surface printed light.
        let hl = Highlighter::new();
        let css = hl
            .stylesheet("Solarized (light)", "base16-ocean.dark")
            .unwrap();

        let screen_start = css
            .find("@media screen")
            .expect("dark override must live inside an @media screen block");
        let dark_selector = css
            .find(":root[data-theme=\"dark\"]")
            .expect("dark override selector missing");
        assert!(
            dark_selector > screen_start,
            "[data-theme=\"dark\"] must be nested inside @media screen, got: {css}"
        );
    }
}
